/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Metadata */
        get: operations["model_metadata_api_v1_model_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_v1_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{simulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation */
        get: operations["get_simulation_api_v1_simulations__simulation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Runs */
        get: operations["list_test_runs_api_v1_test_runs_get"];
        put?: never;
        /** Create Test Run */
        post: operations["create_test_run_api_v1_test_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Test Run */
        post: operations["import_test_run_api_v1_test_runs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs/{test_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Run */
        get: operations["get_test_run_api_v1_test_runs__test_run_id__get"];
        put?: never;
        post?: never;
        /** Delete Test Run */
        delete: operations["delete_test_run_api_v1_test_runs__test_run_id__delete"];
        options?: never;
        head?: never;
        /** Update Test Run */
        patch: operations["update_test_run_api_v1_test_runs__test_run_id__patch"];
        trace?: never;
    };
    "/api/v1/test-runs/{test_run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Test Run */
        get: operations["export_test_run_api_v1_test_runs__test_run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentDocument */
        AttachmentDocument: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Import Warnings */
            import_warnings: string[];
            /** Locally Owned */
            locally_owned: boolean;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Mime Type */
            mime_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** BubbleBin */
        BubbleBin: {
            diameter_nm: components["schemas"]["ValueWithUncertainty"];
            number_per_ml: components["schemas"]["ValueWithUncertainty"];
        };
        /** BubbleDistributionPoint */
        BubbleDistributionPoint: {
            /** Diameter Nm */
            diameter_nm: number;
            /** Number Per Ml */
            number_per_mL: number;
        };
        /** BubblePopulationInput */
        BubblePopulationInput: {
            /** Bins */
            bins?: components["schemas"]["BubbleBin"][];
            hydrogen_content_scale?: components["schemas"]["ValueWithUncertainty"];
            /**
             * Method
             * @default particle-sizing diagnostic; gas identity requires orthogonal confirmation
             */
            method: string;
            surface_tension_n_m?: components["schemas"]["ValueWithUncertainty"];
        };
        /** CalibrationReference */
        CalibrationReference: {
            /** Applies To */
            applies_to?: ("hydrogen_decay.csv" | "bubble_distribution.csv" | "pressure_trace.csv")[];
            /** Calibrated At */
            calibrated_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id: string;
            /**
             * Instrument
             * @default unspecified instrument
             */
            instrument: string;
            /** Method */
            method: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * CfdBoundaryExport
         * @description Neutral homogeneous boundary data, explicitly not a spatial CFD field.
         */
        CfdBoundaryExport: {
            /** Engine Geometry */
            engine_geometry: {
                [key: string]: number;
            };
            /**
             * Export Kind
             * @default homogeneous_0d_boundary_only
             * @constant
             */
            export_kind: "homogeneous_0d_boundary_only";
            /** Mechanism */
            mechanism: string;
            /** Mechanism Sha256 */
            mechanism_sha256: string | null;
            /** Missing Fields */
            missing_fields?: string[];
            /**
             * Schema Version
             * @default 1.0.0
             */
            schema_version: string;
            /** States */
            states: components["schemas"]["HomogeneousBoundaryState"][];
            /** Water Loading Mg Per Cycle */
            water_loading_mg_per_cycle: number;
        };
        /** CombustionInput */
        CombustionInput: {
            combustion_duration_deg?: components["schemas"]["ValueWithUncertainty"];
            combustion_efficiency?: components["schemas"]["ValueWithUncertainty"];
            combustion_start_deg_atdc?: components["schemas"]["ValueWithUncertainty"];
            gate_wall_loss_fraction?: components["schemas"]["ValueWithUncertainty"];
            motored_gamma?: components["schemas"]["ValueWithUncertainty"];
            target_equivalence_ratio?: components["schemas"]["ValueWithUncertainty"];
            wall_temperature_k?: components["schemas"]["ValueWithUncertainty"];
            wiebe_a?: components["schemas"]["ValueWithUncertainty"];
            wiebe_m?: components["schemas"]["ValueWithUncertainty"];
        };
        /** ComparisonCollection */
        ComparisonCollection: {
            /** Items */
            items?: components["schemas"]["ComparisonRecord"][];
        };
        /** ComparisonRecord */
        ComparisonRecord: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "retention" | "pressure_trace" | "simulation";
            /** Label */
            label: string;
            /** Measured Value */
            measured_value?: number | null;
            /** Modeled Value */
            modeled_value?: number | null;
            /** Notes */
            notes?: string | null;
            /** Simulation Id */
            simulation_id?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** CycleTrace */
        CycleTrace: {
            /** Adiabatic Flame Temperature K */
            adiabatic_flame_temperature_k: number | null;
            /** Crank Angle Deg */
            crank_angle_deg: number[];
            /** Cumulative Heat Release J */
            cumulative_heat_release_j: number[];
            /** Cumulative Vaporization Heat J */
            cumulative_vaporization_heat_j: number[];
            /** Cumulative Wall Heat Loss J */
            cumulative_wall_heat_loss_j: number[];
            /** Energy Conservation Residual Fraction */
            energy_conservation_residual_fraction: number;
            /** H2 Mg */
            h2_mg: number[];
            /** H2O Vapor Mg */
            h2o_vapor_mg: number[];
            /** Imep Bar */
            imep_bar: number;
            /**
             * Model Label
             * @default Single-zone state — schematic, not CFD.
             * @constant
             */
            model_label: "Single-zone state — schematic, not CFD.";
            /** N2 Mg */
            n2_mg: number[];
            /** O2 Mg */
            o2_mg: number[];
            /** Pressure Pa */
            pressure_pa: number[];
            /** Pv Work J */
            pv_work_j: number;
            /**
             * Relative Thermal Nox Risk
             * @enum {string}
             */
            relative_thermal_nox_risk: "low" | "moderate" | "high" | "not_applicable";
            /** Temperature K */
            temperature_k: number[];
            uncertainty?: components["schemas"]["TraceUncertaintyBands"] | null;
            /** Upper Bound Indicated Efficiency */
            upper_bound_indicated_efficiency: number | null;
            /** Volume M3 */
            volume_m3: number[];
            /** Water Liquid Mg */
            water_liquid_mg: number[];
            /** Water Vapor Mg */
            water_vapor_mg: number[];
        };
        /** Diagnostic */
        Diagnostic: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
        };
        /**
         * Distribution
         * @enum {string}
         */
        Distribution: "fixed" | "normal" | "lognormal" | "uniform" | "triangular";
        /** EnergyTerms */
        EnergyTerms: {
            /** Estimated Wall Loss J */
            estimated_wall_loss_j: number;
            /** Heat Recovery J */
            heat_recovery_j: number;
            /** Hydrogen Chemical Energy J */
            hydrogen_chemical_energy_j: number;
            /** Net External Preheat J */
            net_external_preheat_j: number;
            /** Target Indicated Work J */
            target_indicated_work_j: number;
            /** Usable Energy Margin J */
            usable_energy_margin_j: number;
            /** Water Phase Change J */
            water_phase_change_j: number;
            /** Water Sensible Heating J */
            water_sensible_heating_j: number;
        };
        /** EngineInput */
        EngineInput: {
            bore_mm?: components["schemas"]["ValueWithUncertainty"];
            compression_ratio?: components["schemas"]["ValueWithUncertainty"];
            connecting_rod_mm?: components["schemas"]["ValueWithUncertainty"];
            displacement_l?: components["schemas"]["ValueWithUncertainty"];
            speed_rpm?: components["schemas"]["ValueWithUncertainty"];
            stroke_mm?: components["schemas"]["ValueWithUncertainty"];
            target_imep_bar?: components["schemas"]["ValueWithUncertainty"];
            volumetric_efficiency?: components["schemas"]["ValueWithUncertainty"];
        };
        /** EnvironmentInput */
        EnvironmentInput: {
            henry_loading_scale?: components["schemas"]["ValueWithUncertainty"];
            hydrogen_headspace_mole_fraction?: components["schemas"]["ValueWithUncertainty"];
            intake_pressure_bar?: components["schemas"]["ValueWithUncertainty"];
            intake_temperature_k?: components["schemas"]["ValueWithUncertainty"];
            water_pressure_bar?: components["schemas"]["ValueWithUncertainty"];
            water_temperature_k?: components["schemas"]["ValueWithUncertainty"];
        };
        /**
         * EvidenceBasis
         * @enum {string}
         */
        EvidenceBasis: "measured" | "literature" | "user_assumption" | "derived" | "synthetic";
        /** EvidenceDocument */
        EvidenceDocument: {
            /** Applicability Note */
            applicability_note: string;
            /** Author Or Publisher */
            author_or_publisher: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Local Attachment */
            local_attachment?: string | null;
            /** Method */
            method: string;
            /** Publication Date */
            publication_date: string;
            /** Title */
            title: string;
            /** Uncertainty */
            uncertainty: string;
            /** Unit */
            unit: string;
            /** Url */
            url?: string | null;
            /** Value Or Range */
            value_or_range: string;
        };
        /** EvidenceInput */
        EvidenceInput: {
            /** Applicability Note */
            applicability_note: string;
            /** Author Or Publisher */
            author_or_publisher: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Local Attachment */
            local_attachment?: string | null;
            /** Method */
            method: string;
            /** Publication Date */
            publication_date: string;
            /** Title */
            title: string;
            /** Uncertainty */
            uncertainty: string;
            /** Unit */
            unit: string;
            /** Url */
            url?: string | null;
            /** Value Or Range */
            value_or_range: string;
        };
        /**
         * EvidenceKind
         * @enum {string}
         */
        EvidenceKind: "measured" | "literature" | "user_assumption";
        /** EvidenceRecord */
        EvidenceRecord: {
            /** Applicability Note */
            applicability_note: string;
            /** Author Or Publisher */
            author_or_publisher: string;
            basis: components["schemas"]["EvidenceRecordBasis"];
            /** Id */
            id: string;
            /** Local Attachment */
            local_attachment?: string | null;
            /** Method */
            method: string;
            /** Publication Date */
            publication_date?: string | null;
            /** Title */
            title: string;
            /** Uncertainty */
            uncertainty: string;
            /** Unit */
            unit: string;
            /** Url */
            url?: string | null;
            /** Value Or Range */
            value_or_range: string;
        };
        /**
         * EvidenceRecordBasis
         * @description Allowed provenance classes for a complete evidence ledger record.
         * @enum {string}
         */
        EvidenceRecordBasis: "measured" | "literature" | "user_assumption";
        /**
         * FailureCode
         * @enum {string}
         */
        FailureCode: "invalid_data" | "mass_balance_failed" | "insufficient_h2" | "preheat_deficit" | "outside_model_domain" | "pass";
        /** GateResult */
        GateResult: {
            /**
             * Ambient H2 Lfl Volume Percent Safety Reference
             * @default 4
             */
            ambient_h2_lfl_volume_percent_safety_reference: number;
            /** Domain Warnings */
            domain_warnings?: string[];
            energy_terms: components["schemas"]["EnergyTerms"];
            /** Failures */
            failures: components["schemas"]["FailureCode"][];
            hydrogen_available: components["schemas"]["ValueWithUncertainty"];
            /** Hydrogen Mass Margin Mg Per Cycle */
            hydrogen_mass_margin_mg_per_cycle: number;
            hydrogen_required: components["schemas"]["ValueWithUncertainty"];
            mass_balance: components["schemas"]["MassBalance"];
            /** Oxygen Available Mg Per Cycle */
            oxygen_available_mg_per_cycle: number;
            /** Passed */
            passed: boolean;
            /** Trapped Air Mg Per Cycle */
            trapped_air_mg_per_cycle: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatRecoveryInput */
        HeatRecoveryInput: {
            recovered_heat_j_per_cycle?: components["schemas"]["ValueWithUncertainty"];
        };
        /** HomogeneousBoundaryState */
        HomogeneousBoundaryState: {
            /** Crank Angle Deg */
            crank_angle_deg: number;
            /** Mole Fractions */
            mole_fractions: {
                [key: string]: number;
            };
            /** Pressure Pa */
            pressure_pa: number;
            /** Temperature K */
            temperature_k: number;
            /** Volume M3 */
            volume_m3: number;
        };
        /** HydrogenDecayPoint */
        HydrogenDecayPoint: {
            /** Time S */
            time_s: number;
            /** Total H2 Mg L */
            total_h2_mg_L: number;
            /** Uncertainty Mg L */
            uncertainty_mg_L: number;
        };
        /** HydrogenLoadingResult */
        HydrogenLoadingResult: {
            bubble_contained_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
            /** Bubble Contribution Counted */
            bubble_contribution_counted: boolean;
            /** Bubble Method Limitation */
            bubble_method_limitation: string;
            chemical_energy_density_kj_l: components["schemas"]["ValueWithUncertainty"];
            dissolved_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "measured_total" | "derived";
            total_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
        };
        /** ImportedAttachmentDocument */
        ImportedAttachmentDocument: {
            /** Canonical Name */
            canonical_name: string;
            /** Id */
            id: string;
            /** Import Warnings */
            import_warnings: string[];
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ImportedSimulationLink */
        ImportedSimulationLink: {
            /** Persisted Id */
            persisted_id: string;
            /** Source Id */
            source_id: string | null;
        };
        /** Interval95 */
        Interval95: {
            /** Lower */
            lower: number;
            /** Median */
            median: number;
            /** Unit */
            unit: string;
            /** Upper */
            upper: number;
        };
        /** MassBalance */
        MassBalance: {
            /** Initial H2 Mg Per Cycle */
            initial_h2_mg_per_cycle: number;
            /** Relative Residual */
            relative_residual: number;
            /** Released H2 Mg Per Cycle */
            released_h2_mg_per_cycle: number;
            /** Residual H2 Mg Per Cycle */
            residual_h2_mg_per_cycle: number;
            /** Retained H2 Mg Per Cycle */
            retained_h2_mg_per_cycle: number;
            /** Unaccounted H2 Mg Per Cycle */
            unaccounted_h2_mg_per_cycle: number;
        };
        /**
         * MeasuredValue
         * @description A populated scalar measurement; unlike simulation defaults, provenance is required.
         */
        MeasuredValue: {
            /**
             * Basis
             * @constant
             */
            basis: "measured";
            /**
             * Distribution
             * @enum {string}
             */
            distribution: "normal" | "uniform" | "triangular";
            /** Source Id */
            source_id: string;
            /** Standard Uncertainty */
            standard_uncertainty: number;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * MeasurementRecord
         * @description A canonical scalar measurement with units, uncertainty, and method linkage.
         */
        MeasurementRecord: {
            /** Calibration Reference Id */
            calibration_reference_id: string;
            /** Method */
            method: string;
            /** Name */
            name: string;
            value: components["schemas"]["MeasuredValue"];
        };
        /** ModelMetadata */
        ModelMetadata: {
            /** Cantera Version */
            cantera_version: string | null;
            /** Equations */
            equations: {
                [key: string]: string;
            };
            /** Limitations */
            limitations: string[];
            /** Mechanism */
            mechanism: string;
            /** Mechanism Sha256 */
            mechanism_sha256: string | null;
            /** Model Version */
            model_version: string;
            /** Parameter Definitions */
            parameter_definitions: {
                [key: string]: string;
            };
            /** Schema Version */
            schema_version: string;
            /** Source Ledger */
            source_ledger: components["schemas"]["EvidenceRecord"][];
            /** Valid Domains */
            valid_domains: {
                [key: string]: string;
            };
        };
        /** PressureTracePoint */
        PressureTracePoint: {
            /** Crank Angle Deg */
            crank_angle_deg: number;
            /** Pressure Bar */
            pressure_bar: number;
            /** Uncertainty Bar */
            uncertainty_bar: number;
        };
        /** ReproducibilityMetadata */
        ReproducibilityMetadata: {
            /** Analytical Samples */
            analytical_samples: number;
            /** Cantera Available */
            cantera_available: boolean;
            /** Cantera Version */
            cantera_version: string | null;
            /** Cycle Samples */
            cycle_samples: number;
            /** Mechanism */
            mechanism: string;
            /** Mechanism Sha256 */
            mechanism_sha256: string | null;
            /** Model Version */
            model_version: string;
            /** Numpy Version */
            numpy_version: string;
            /** Python Version */
            python_version: string;
            /** Random Seed */
            random_seed: number;
            /** Schema Version */
            schema_version: string;
            /** Scipy Version */
            scipy_version: string;
            /** Solver Version */
            solver_version: string;
        };
        /** RetentionInput */
        RetentionInput: {
            elapsed_time_s?: components["schemas"]["ValueWithUncertainty"];
            first_order_rate_constant_per_s?: components["schemas"]["ValueWithUncertainty"];
            handling_loss_fraction?: components["schemas"]["ValueWithUncertainty"];
            intake_delivery_fraction?: components["schemas"]["ValueWithUncertainty"];
            /** Measured Time Series */
            measured_time_series?: components["schemas"]["RetentionMeasurement"][];
            /**
             * Release Method
             * @default passive transfer to intake; user assumption
             */
            release_method: string;
            reported_released_fraction?: components["schemas"]["ValueWithUncertainty"];
        };
        /** RetentionMeasurement */
        RetentionMeasurement: {
            /** Time S */
            time_s: number;
            total_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
        };
        /** RetentionResult */
        RetentionResult: {
            /** Elapsed Time S */
            elapsed_time_s: number;
            handling_loss_fraction: components["schemas"]["ValueWithUncertainty"];
            initial_total_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
            intake_delivery_fraction: components["schemas"]["ValueWithUncertainty"];
            /**
             * Method
             * @enum {string}
             */
            method: "measured_time_series" | "first_order_assumption";
            pre_handling_retention_fraction: components["schemas"]["ValueWithUncertainty"];
            /** Pressure Bar */
            pressure_bar: number;
            /** Release Method */
            release_method: string;
            released_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
            retained_at_intake_mg_l: components["schemas"]["ValueWithUncertainty"];
            retained_fraction: components["schemas"]["ValueWithUncertainty"];
            /** Temperature K */
            temperature_k: number;
            unaccounted_h2_mg_l: components["schemas"]["ValueWithUncertainty"];
        };
        /** SampleInput */
        SampleInput: {
            carrier_volume_ml_per_cycle?: components["schemas"]["ValueWithUncertainty"];
            measured_total_h2_mg_l?: components["schemas"]["ValueWithUncertainty"];
            separate_h2_mg_per_cycle?: components["schemas"]["ValueWithUncertainty"];
            water_injection_mg_per_cycle?: components["schemas"]["ValueWithUncertainty"];
            water_volume_l?: components["schemas"]["ValueWithUncertainty"];
        };
        /**
         * Scenario
         * @enum {string}
         */
        Scenario: "upstream_vaporized_carrier" | "hydrogen_with_water_injection";
        /** SensitivityEntry */
        SensitivityEntry: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "increases" | "decreases" | "neutral";
            /** Normalized Effect */
            normalized_effect: number;
            /** Output Metric */
            output_metric: string;
            /** Parameter */
            parameter: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "error";
        /** SimulationInput */
        SimulationInput: {
            bubble_population?: components["schemas"]["BubblePopulationInput"] | null;
            combustion?: components["schemas"]["CombustionInput"];
            engine?: components["schemas"]["EngineInput"];
            environment?: components["schemas"]["EnvironmentInput"];
            heat_recovery?: components["schemas"]["HeatRecoveryInput"];
            retention?: components["schemas"]["RetentionInput"];
            sample?: components["schemas"]["SampleInput"];
            /** @default upstream_vaporized_carrier */
            scenario: components["schemas"]["Scenario"];
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            uncertainty?: components["schemas"]["UncertaintySettings"];
        };
        /** SimulationResult */
        SimulationResult: {
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRecord"][];
            gate: components["schemas"]["GateResult"];
            input: components["schemas"]["SimulationInput"];
            loading: components["schemas"]["HydrogenLoadingResult"];
            motored_baseline: components["schemas"]["CycleTrace"];
            proposed_cycle: components["schemas"]["CycleTrace"] | null;
            reproducibility: components["schemas"]["ReproducibilityMetadata"];
            /** Result Id */
            result_id: string;
            retention: components["schemas"]["RetentionResult"];
            /** Sensitivity */
            sensitivity?: components["schemas"]["SensitivityEntry"][];
            uncertainty: components["schemas"]["UncertaintyResult"];
        };
        /**
         * TestRun
         * @description Canonical persisted test-run document exposed by import/export contracts.
         */
        TestRun: {
            /** Attachments */
            attachments: components["schemas"]["AttachmentDocument"][];
            /** Calibration References */
            calibration_references: components["schemas"]["CalibrationReference"][];
            comparisons: components["schemas"]["ComparisonCollection"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceDocument"][];
            /** Id */
            id: string;
            /** Is Demo Synthetic */
            is_demo_synthetic: boolean;
            measurements: components["schemas"]["TestRunMeasurements"];
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Operator */
            operator: string | null;
            provenance: components["schemas"]["TestRunProvenance"];
            /** Sample Id */
            sample_id: string | null;
            /** Simulation Ids */
            simulation_ids: string[];
            status: components["schemas"]["TestRunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TestRunCreate */
        TestRunCreate: {
            /** Calibration References */
            calibration_references?: components["schemas"]["CalibrationReference"][];
            comparisons?: components["schemas"]["ComparisonCollection"];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceInput"][];
            /**
             * Is Demo Synthetic
             * @default false
             */
            is_demo_synthetic: boolean;
            measurements?: components["schemas"]["TestRunMeasurements"];
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Operator */
            operator?: string | null;
            provenance?: components["schemas"]["TestRunProvenance"];
            /** Sample Id */
            sample_id?: string | null;
            /** @default draft */
            status: components["schemas"]["TestRunStatus"];
        };
        /** TestRunDocument */
        TestRunDocument: {
            /** Attachments */
            attachments: components["schemas"]["AttachmentDocument"][];
            /** Calibration References */
            calibration_references: components["schemas"]["CalibrationReference"][];
            comparisons: components["schemas"]["ComparisonCollection"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceDocument"][];
            /** Id */
            id: string;
            /** Is Demo Synthetic */
            is_demo_synthetic: boolean;
            measurements: components["schemas"]["TestRunMeasurements"];
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Operator */
            operator: string | null;
            provenance: components["schemas"]["TestRunProvenance"];
            /** Sample Id */
            sample_id: string | null;
            /** Simulation Ids */
            simulation_ids: string[];
            status: components["schemas"]["TestRunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TestRunImportResponse */
        TestRunImportResponse: {
            attachment: components["schemas"]["ImportedAttachmentDocument"];
            /** Imported Simulations */
            imported_simulations: components["schemas"]["ImportedSimulationLink"][];
            test_run: components["schemas"]["TestRun"];
        };
        /**
         * TestRunMeasurements
         * @description Typed measurement ledger; missing scalar values remain explicit ``null``.
         */
        TestRunMeasurements: {
            bubble_diameter_nm?: components["schemas"]["MeasuredValue"] | null;
            /** Bubble Distribution.Csv */
            "bubble_distribution.csv"?: components["schemas"]["BubbleDistributionPoint"][] | null;
            elapsed_s?: components["schemas"]["MeasuredValue"] | null;
            headspace_gc_mg_l?: components["schemas"]["MeasuredValue"] | null;
            /** Hydrogen Decay.Csv */
            "hydrogen_decay.csv"?: components["schemas"]["HydrogenDecayPoint"][] | null;
            number_per_ml?: components["schemas"]["MeasuredValue"] | null;
            pressure_pa_abs?: components["schemas"]["MeasuredValue"] | null;
            /** Pressure Trace.Csv */
            "pressure_trace.csv"?: components["schemas"]["PressureTracePoint"][] | null;
            released_h2_mg_l?: components["schemas"]["MeasuredValue"] | null;
            retained_h2_mg_l?: components["schemas"]["MeasuredValue"] | null;
            retention_fraction?: components["schemas"]["MeasuredValue"] | null;
            /** Scalar Measurements */
            scalar_measurements?: components["schemas"]["MeasurementRecord"][];
            temperature_k?: components["schemas"]["MeasuredValue"] | null;
            total_h2_mg_l?: components["schemas"]["MeasuredValue"] | null;
            unaccounted_h2_mg_l?: components["schemas"]["MeasuredValue"] | null;
        };
        /** TestRunPatch */
        TestRunPatch: {
            /** Calibration References */
            calibration_references?: components["schemas"]["CalibrationReference"][] | null;
            comparisons?: components["schemas"]["ComparisonCollection"] | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceInput"][] | null;
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
            /** Is Demo Synthetic */
            is_demo_synthetic?: boolean | null;
            measurements?: components["schemas"]["TestRunMeasurements"] | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Operator */
            operator?: string | null;
            provenance?: components["schemas"]["TestRunProvenance"] | null;
            /** Sample Id */
            sample_id?: string | null;
            status?: components["schemas"]["TestRunStatus"] | null;
        };
        /** TestRunProvenance */
        TestRunProvenance: {
            /** Import Sha256 */
            import_sha256?: string | null;
            /**
             * Is Demo Synthetic
             * @default false
             */
            is_demo_synthetic: boolean;
            /** Method */
            method?: string | null;
            /** Source */
            source?: string | null;
            /** Source Test Run Id */
            source_test_run_id?: string | null;
            /** Ui Origin */
            ui_origin?: string | null;
        };
        /**
         * TestRunStatus
         * @enum {string}
         */
        TestRunStatus: "draft" | "needs_review" | "valid" | "invalid";
        /** TraceUncertaintyBands */
        TraceUncertaintyBands: {
            /** Accepted Cycle Samples */
            accepted_cycle_samples: number;
            /** Pressure Lower 95 Pa */
            pressure_lower_95_pa: number[];
            /** Pressure Upper 95 Pa */
            pressure_upper_95_pa: number[];
            /** Temperature Lower 95 K */
            temperature_lower_95_k: number[];
            /** Temperature Upper 95 K */
            temperature_upper_95_k: number[];
        };
        /** UncertaintyResult */
        UncertaintyResult: {
            /** Analytical Samples */
            analytical_samples: number;
            /** Cycle Samples Requested */
            cycle_samples_requested: number;
            /** Enabled */
            enabled: boolean;
            energy_margin_95: components["schemas"]["Interval95"];
            /** Gate Pass Probability */
            gate_pass_probability: number;
            hydrogen_available_95: components["schemas"]["Interval95"];
            /**
             * Method
             * @default seeded_latin_hypercube
             * @constant
             */
            method: "seeded_latin_hypercube";
            /** Seed */
            seed: number;
            /** Sensitivities */
            sensitivities: components["schemas"]["SensitivityEntry"][];
        };
        /** UncertaintySettings */
        UncertaintySettings: {
            /**
             * Analytical Samples
             * @default 200
             */
            analytical_samples: number;
            /**
             * Cycle Samples
             * @default 64
             */
            cycle_samples: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Seed
             * @default 20260824
             */
            seed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValueWithUncertainty
         * @description A scalar with canonical unit, one-sigma uncertainty, and provenance.
         */
        ValueWithUncertainty: {
            /** @default user_assumption */
            basis: components["schemas"]["EvidenceBasis"];
            /** @default fixed */
            distribution: components["schemas"]["Distribution"];
            /** Source Id */
            source_id?: string | null;
            /**
             * Standard Uncertainty
             * @default 0
             */
            standard_uncertainty: number;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    model_metadata_api_v1_model_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMetadata"];
                };
            };
        };
    };
    evaluate_api_v1_simulations_post: {
        parameters: {
            query?: {
                persist?: boolean;
                test_run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_api_v1_simulations__simulation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_runs_api_v1_test_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunDocument"][];
                };
            };
        };
    };
    create_test_run_api_v1_test_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_test_run_api_v1_test_runs_import_post: {
        parameters: {
            query?: {
                filename?: string | null;
                test_run_id?: string | null;
                expected_updated_at?: string | null;
                calibration_reference?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_run_api_v1_test_runs__test_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_run_api_v1_test_runs__test_run_id__delete: {
        parameters: {
            query: {
                expected_updated_at: string;
                /** @description Explicit UI/user confirmation */
                confirm?: boolean;
            };
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_run_api_v1_test_runs__test_run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRunPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_test_run_api_v1_test_runs__test_run_id__export_get: {
        parameters: {
            query: {
                expected_updated_at: string;
                format?: string;
                simulation_id?: string | null;
            };
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical JSON, reviewed CSV ZIP, or neutral homogeneous 0D boundary export. The named JSON schema applies to format=cfd_boundary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CfdBoundaryExport"];
                    "application/zip": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
